# This file defines the build, push, and deploy steps for a Cloud Run service.

steps:
  # Step 1: Build the Docker image
  # This step uses the official Docker builder to create the container image.
- id: 'Docker Build'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', '-t',
    'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/kg-mcp',
    '.'
  ]

  # Step 2: Push the Docker image to Artifact Registry
  # This step pushes the newly built image to Google Artifact Registry.
  # It depends on the 'Docker Build' step completing successfully.
- id: 'Docker Push'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/kg-mcp'
  ]
  waitFor: ['Docker Build']

  # Step 3: Fetch environment variables from Doppler
  # This step fetches all environment variables from Doppler and saves them to a file.
- id: 'Fetch Doppler Secrets'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh | sh
      doppler secrets download --no-file --format env-no-quotes > /workspace/.env.cloud
  secretEnv: ['DOPPLER_TOKEN']
  waitFor: ['Docker Push']

  # Step 4: Deploy the image to Cloud Run
  # This step uses the gcloud builder to deploy the container.
  # It depends on the 'Fetch Doppler Secrets' step completing successfully.
- id: 'Deploy to Cloud Run'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run deploy kg-mcp \
        --image us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/kg-mcp \
        --region us-central1 \
        --platform managed \
        --memory 4Gi \
        --min-instances 1 \
        --allow-unauthenticated \
        --env-vars-file=/workspace/.env.cloud
  waitFor: ['Fetch Doppler Secrets']

# Specify the image to be pushed to Artifact Registry upon successful build.
images:
- 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/kg-mcp'

# Make secrets available to build steps
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/DOPPLER_TOKEN/versions/latest
    env: 'DOPPLER_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY
